spring:
  application:
    name: fraud-detection-system

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: fraud-alert-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.fraud_detection_system.model"

    streams:
      application-id: fraud-detection-streams
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.springframework.kafka.support.serializer.JsonSerde
      properties:
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

spring.json.trusted.packages: "com.example.fraud_detection_system.model"
fraud:
  rules:
    large-transaction-threshold: 10000.00
    velocity-transaction-count: 5
    velocity-window-seconds: 60